Repository zmap/zgrab2, pull requests merged in 2024-04, with the labels that each got.

#421 Update config.go
  config.go
Labels: bug

#417 Docs: Add Module Help Usage to README
  README.md
Labels: documentation

#423 Fix Parser for ModuleIdentificationRequest of s7 Protocol
  modules/siemens/s7.go
Labels: bug

#422 Add support for custom DNS server
  config.go
  conn.go
  utility.go
Labels: enhancement

#412 Add HaSSH to ssh output
  lib/ssh/messages.go
  lib/ssh/messages_test.go
Labels: enhancement
