Repository zmap/zgrab2, pull requests merged in 2025-01, with the labels that each got.

#478 fix: failing ci tests
  .github/workflows/integration-test.yml
  modules/http/http_readlimit_test.go
Labels: github_actions

#470 Add support for PPTP
  integration_tests/pptp/chap-secrets
  integration_tests/pptp/cleanup.sh
  integration_tests/pptp/setup.sh
  integration_tests/pptp/test.sh
  modules/pptp.go
  modules/pptp/scanner.go
  zgrab2_schemas/zgrab2/__init__.py
  zgrab2_schemas/zgrab2/pptp.py
Labels: new protocol

#467 Add support for MQTT v3.1.1 and v5.0
  integration_tests/mqtt/cleanup.sh
  integration_tests/mqtt/mosquitto.conf
  integration_tests/mqtt/multiple.ini
  integration_tests/mqtt/server.crt
  integration_tests/mqtt/server.csr
  integration_tests/mqtt/server.key
  integration_tests/mqtt/server.pem
  integration_tests/mqtt/setup.sh
  integration_tests/mqtt/test.sh
  modules/mqtt.go
  modules/mqtt/scanner.go
  zgrab2_schemas/zgrab2/__init__.py
  zgrab2_schemas/zgrab2/mqtt.py
Labels: new protocol

#471 Add support for socks5
  integration_tests/socks5/3proxy.cfg
  integration_tests/socks5/cleanup.sh
  integration_tests/socks5/setup.sh
  integration_tests/socks5/test.sh
  modules/socks5.go
  modules/socks5/scanner.go
  zgrab2_schemas/zgrab2/__init__.py
  zgrab2_schemas/zgrab2/socks5.py
Labels: new protocol

#335 Fix ssh
  modules/ssh.go
Labels: module/ssh
